services:
#  moder-api:
#    build: .
#    ports:
#      - "8001:8001"
  telegram_bot:
    image: ghcr.io/labubu-team/labubu-tgbot:latest
    pull_policy: always
    environment:
      SERVICE_ACCOUNT_ID: ${SERVICE_ACCOUNT_ID:?SERVICE_ACCOUNT_ID is required}
      PUBLIC_KEY: ${PUBLIC_KEY:?PUBLIC_KEY is required}
      PRIVATE_KEY: ${PRIVATE_KEY:?PRIVATE_KEY is required}
      KEY_ID: ${KEY_ID:?KEY_ID is required}
      FOLDER_ID: ${FOLDER_ID:?FOLDER_ID is required}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:?TELEGRAM_TOKEN is required}
      S3_ENDPOINT: ${S3_ENDPOINT:?S3_ENDPOINT is required}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}
      S3_BUCKET: ${S3_BUCKET:? S3_BUCKET is required}
      # S3_PREFIX: ${S3_PREFIX:?S3_PREFIX is required}
    networks:
      - labubu_net
  rag:
    image: ghcr.io/labubu-team/labubu-rag:latest
    pull_policy: always
    command: ["uvicorn", "yanka:app", "--host", "0.0.0.0", "--port", "7999"]
    networks:
      - labubu_net

networks:
  labubu_net:
    driver: bridge