version: '3.8'

services:
  moder-api:
    build: .
    ports:
      - "8001:8001"
  telegram-bot:
    build: .
    ports:
      - "8000:8000"
  moder-regex:
    build: .
    ports:
      - "8002:8002"