name: Release Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push Telegram Bot Image
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/urfu-llm-agent

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./telegram_bot/Dockerfile \
            -t $REPO:latest \
            -t $REPO:${{ github.run_number }} \
            --push \
            .